"""Demo catalog rows (mirrors frontend/src/data/products.ts). Used for DB seed / force upsert."""

from typing import Any

CATALOG_ROWS: list[dict[str, Any]] = [
    {
        "slug": "amity-scholar-sketch-tee-white",
        "name": "Amity Scholar Sketch Oversized T-shirt",
        "brand": "Rigo",
        "category": "apparels",
        "sub_category": "T-Shirts",
        "price": 1119,
        "mrp": 1499,
        "rating": 4.8,
        "reviews": 142,
        "image_path": "/catalog/product-tshirt-white.jpg",
        "colors": ["White", "Navy"],
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "tags": ["oversized", "graphic", "unisex"],
        "best_seller": True,
        "new_arrival": False,
        "active": True,
    },
    {
        "slug": "amity-digital-revolution-tee-white",
        "name": "Amity Digital Revolution Oversized T-shirt",
        "brand": "Rigo",
        "category": "apparels",
        "sub_category": "T-Shirts",
        "price": 1119,
        "mrp": 1499,
        "rating": 4.7,
        "reviews": 98,
        "image_path": "/catalog/product-tshirt-white.jpg",
        "colors": ["White"],
        "sizes": ["S", "M", "L", "XL"],
        "tags": ["oversized", "graphic"],
        "best_seller": True,
        "new_arrival": False,
        "active": True,
    },
    {
        "slug": "amity-cm-tee-navy",
        "name": "Amity CM Classic T-shirt",
        "brand": "Rigo",
        "category": "apparels",
        "sub_category": "T-Shirts",
        "price": 899,
        "mrp": 1199,
        "rating": 4.6,
        "reviews": 76,
        "image_path": "/catalog/product-tshirt-navy.jpg",
        "colors": ["Navy", "Yellow"],
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "tags": ["classic"],
        "best_seller": False,
        "new_arrival": True,
        "active": True,
    },
    {
        "slug": "campus-merch-hoodie-navy",
        "name": "Campus Merch Signature Hoodie",
        "brand": "Rigo",
        "category": "apparels",
        "sub_category": "Hoodies",
        "price": 1899,
        "mrp": 2499,
        "rating": 4.9,
        "reviews": 211,
        "image_path": "/catalog/product-hoodie.jpg",
        "colors": ["Navy", "Black"],
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "tags": ["fleece", "signature"],
        "best_seller": True,
        "new_arrival": False,
        "active": True,
    },
    {
        "slug": "cm-coffee-mug-navy",
        "name": "CM Ceramic Coffee Mug",
        "brand": "House of Quirk",
        "category": "drinkware",
        "sub_category": "Mugs",
        "price": 449,
        "mrp": 599,
        "rating": 4.7,
        "reviews": 187,
        "image_path": "/catalog/product-mug.jpg",
        "colors": ["Navy"],
        "sizes": None,
        "tags": ["ceramic", "350ml"],
        "best_seller": False,
        "new_arrival": False,
        "active": True,
    },
    {
        "slug": "amity-stainless-bottle",
        "name": "Amity Stainless Steel Bottle 750ml",
        "brand": "House of Quirk",
        "category": "drinkware",
        "sub_category": "Bottles",
        "price": 999,
        "mrp": 1299,
        "rating": 4.8,
        "reviews": 132,
        "image_path": "/catalog/product-bottle.jpg",
        "colors": ["Navy", "Yellow"],
        "sizes": None,
        "tags": ["insulated", "750ml"],
        "best_seller": False,
        "new_arrival": True,
        "active": True,
    },
    {
        "slug": "cm-canvas-tote-yellow",
        "name": "CM Canvas Tote Bag",
        "brand": "Bagskart",
        "category": "accessories",
        "sub_category": "Bags",
        "price": 599,
        "mrp": 799,
        "rating": 4.6,
        "reviews": 91,
        "image_path": "/catalog/product-tote.jpg",
        "colors": ["Yellow", "Navy"],
        "sizes": None,
        "tags": ["canvas", "eco"],
        "best_seller": False,
        "new_arrival": False,
        "active": True,
    },
    {
        "slug": "cm-snapback-cap-yellow",
        "name": "CM Snapback Cap",
        "brand": "Bagskart",
        "category": "accessories",
        "sub_category": "Caps",
        "price": 549,
        "mrp": 749,
        "rating": 4.5,
        "reviews": 64,
        "image_path": "/catalog/product-cap.jpg",
        "colors": ["Yellow", "Navy"],
        "sizes": None,
        "tags": ["snapback"],
        "best_seller": False,
        "new_arrival": False,
        "active": True,
    },
    {
        "slug": "amity-scholar-tee-navy",
        "name": "Amity Scholar Tee Navy",
        "brand": "Rigo",
        "category": "apparels",
        "sub_category": "T-Shirts",
        "price": 999,
        "mrp": 1399,
        "rating": 4.5,
        "reviews": 53,
        "image_path": "/catalog/product-tshirt-navy.jpg",
        "colors": ["Navy"],
        "sizes": ["S", "M", "L", "XL"],
        "tags": ["graphic"],
        "best_seller": False,
        "new_arrival": False,
        "active": True,
    },
    {
        "slug": "campus-merch-hoodie-zip",
        "name": "Campus Merch Zip Hoodie",
        "brand": "Rigo",
        "category": "apparels",
        "sub_category": "Hoodies",
        "price": 2199,
        "mrp": 2799,
        "rating": 4.7,
        "reviews": 47,
        "image_path": "/catalog/product-hoodie.jpg",
        "colors": ["Navy"],
        "sizes": ["M", "L", "XL"],
        "tags": ["zip", "fleece"],
        "best_seller": False,
        "new_arrival": False,
        "active": True,
    },
    {
        "slug": "cm-travel-mug",
        "name": "CM Travel Mug 400ml",
        "brand": "House of Quirk",
        "category": "drinkware",
        "sub_category": "Mugs",
        "price": 699,
        "mrp": 899,
        "rating": 4.6,
        "reviews": 38,
        "image_path": "/catalog/product-mug.jpg",
        "colors": ["Navy"],
        "sizes": None,
        "tags": ["travel", "insulated"],
        "best_seller": False,
        "new_arrival": False,
        "active": True,
    },
    {
        "slug": "cm-laptop-sleeve",
        "name": "CM Padded Laptop Sleeve 14 inch",
        "brand": "Bagskart",
        "category": "accessories",
        "sub_category": "Tech",
        "price": 899,
        "mrp": 1199,
        "rating": 4.4,
        "reviews": 29,
        "image_path": "/catalog/product-tote.jpg",
        "colors": ["Navy"],
        "sizes": None,
        "tags": ["padded", "14inch"],
        "best_seller": False,
        "new_arrival": True,
        "active": True,
    },
]
